[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "pip install --upgrade yt-dlp instaloader"
]

[start]
cmd = "node src/index.js"